// src/pages/Disclaimer.jsx
import React from "react";
import { Box, Typography, Container, Button, Stack } from "@mui/material";
import { useNavigate } from "react-router-dom";

export default function Disclaimer() {
  const navigate = useNavigate();

  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Stack spacing={2}>
        <Typography variant="h4" gutterBottom>
          Disclaimer
        </Typography>

        <Typography paragraph>
          NoteWell AI is an assistive documentation tool designed to help mental
          health professionals draft and organize clinical documentation. It does
          not provide medical, mental health, legal, billing, compliance, or
          professional advice.
        </Typography>

        <Typography paragraph>
          Content generated by NoteWell AI is a draft only. You are solely
          responsible for reviewing, editing, approving, and determining whether
          any generated content is accurate, appropriate, complete, and suitable
          for your clinical, ethical, legal, payer, employer, and licensing
          requirements.
        </Typography>

        <Typography paragraph>
          NoteWell AI does not establish a provider-client relationship, does not
          diagnose, does not recommend treatment, and does not replace clinical
          judgment, supervision, consultation, or professional standards of care.
        </Typography>

        <Typography paragraph>
          Do not enter information unless you are authorized to do so and are
          using the application in accordance with your professional obligations,
          workplace policies, and applicable laws.
        </Typography>

        <Typography paragraph>
          NoteWell AI is not liable for documentation errors, omissions,
          clinical decisions, billing decisions, payer disputes, audit outcomes,
          or any damages arising from use or misuse of generated content.
        </Typography>

        <Typography variant="body2" color="text.secondary">
          Last updated: {new Date().toLocaleDateString()}
        </Typography>

        <Box sx={{ pt: 2 }}>
          <Button variant="contained" onClick={() => navigate("/dashboard")}>
            Back to Dashboard
          </Button>
        </Box>
      </Stack>
    </Container>
  );
}