// src/pages/Disclaimer.jsx
import React from "react";
import { Box, Typography, Container } from "@mui/material";

export default function Disclaimer() {
  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Typography variant="h4" gutterBottom>
        Disclaimer
      </Typography>

      <Typography paragraph>
        The information generated by the SOAP App is for general documentation
        assistance only. It does not constitute medical, legal, or clinical
        advice. Use of this application does not establish a provider-client
        relationship.
      </Typography>

      <Typography paragraph>
        You are responsible for reviewing, editing, and ensuring that all content
        meets the standards, ethics, and documentation requirements of your
        license, employer, and state or country.
      </Typography>

      <Typography paragraph>
        SOAP App is not liable for any damages arising from misuse or reliance on
        generated content.
      </Typography>

      <Typography variant="body2" mt={4}>
        Last updated: {new Date().toLocaleDateString()}
      </Typography>
    </Container>
  );
}
